### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by tobyweston** [kadualon/initialState-java#2]
Hey,

Nice project, mind if I use it in my Apache 2.0 project? I can't find a Jar in a maven repo so mind if I include the source with attribution?

**Comment by kadualon** [comment]
Hi,
I need to make sure the code is accessible via maven. 
In the meantime feel free to include the source with attribution. 

Alon Kadury

**Comment by tobyweston** [comment]
Great thanks. Will keep you posted if anything comes of it...
